# Schema for the theme setting configuration file of the THEMETITLE theme.

THEMENAME.settings:
  type: theme_settings
  label: 'THEMETITLE settings'
  mapping:
    cdn_provider:
      type: string
      label: 'CDN Provider'
    breadcrumb_home:
      type: integer
      label: 'Breadcrumb Home'
